// Auto-generated presentation data
// Do not edit this file manually - it's generated by scripts/generate-presentation-data.ts

export interface PresentationInfo {
	id: string
	title: string
	description?: string
	author?: string
	keywords?: string
	theme?: string
	url: string
	topics: string[]
}

export const presentations: PresentationInfo[] = [
  {
    "id": "claude-code-configuration",
    "title": "Claude Code Configuration",
    "description": "## Claude Code Configuration\n\nMastering AI-Powered Development in Your Terminal\n",
    "theme": "default",
    "url": "/talks/claude-code-configuration/",
    "topics": []
  }
]

export function findPresentationById(id: string): PresentationInfo | undefined {
	return presentations.find(p => p.id === id)
}

export function getPresentationRoutes(): string[] {
	return presentations.map(p => p.url)
}
